spring.application.name=spring-boot-backend

# Database - Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/warden
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Redis Cloud Configuration
spring.data.redis.host=redis-18483.c334.asia-southeast2-1.gce.cloud.redislabs.com:18483
spring.data.redis.port=18483
spring.data.redis.username=default
spring.data.redis.password=ueiHOLZzeDSpEjSjdMxg4YeslZnDXvFu

# Optional: Connection Timeout & Pooling
spring.data.redis.timeout=5000

# RabbitMQ
spring.rabbitmq.addresses=amqps://ovksenqm:V-nNSY3rs-0gH8XGtSD23uilwUxNyQZE@dingo.rmq.cloudamqp.com/ovksenqm
#spring.rabbitmq.host=dingo.rmq.cloudamqp.com
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=ovksenqm
#spring.rabbitmq.password=V-nNSY3rs-0gH8XGtSD23uilwUxNyQZE
#spring.rabbitmq.virtual-host=ovksenqm
#spring.rabbitmq.ssl.enabled=true
