# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: live_simulation.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'live_simulation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15live_simulation.proto\x12)org.example.springbootbackend.model.proto\"\xd4\x01\n\x19LiveTransactionEventProto\x12\x0e\n\x06userId\x18\x01 \x01(\x05\x12\r\n\x05txnId\x18\x02 \x01(\t\x12\x0e\n\x06txnAmt\x18\x03 \x01(\x05\x12\x12\n\ntxnTimeUTC\x18\x04 \x01(\x03\x12\x18\n\x10txnTimeLocalHour\x18\x05 \x01(\x05\x12\x0e\n\x06txnLat\x18\x06 \x01(\x02\x12\x0e\n\x06txnLon\x18\x07 \x01(\x02\x12\x12\n\ntxnCountry\x18\x08 \x01(\t\x12\x14\n\x0cmerchantType\x18\t \x01(\t\x12\x10\n\x08\x64\x65viceId\x18\n \x01(\t\"\x9c\x01\n\x1bLiveSimulationEnvelopeProto\x12\x11\n\tchunkSize\x18\x01 \x01(\x05\x12\x13\n\x0bisLastChunk\x18\x02 \x01(\x08\x12U\n\x07payload\x18\x03 \x03(\x0b\x32\x44.org.example.springbootbackend.model.proto.LiveTransactionEventProto\"\xf3\x02\n\x17LiveInferenceEventProto\x12\r\n\x05txnId\x18\x01 \x01(\t\x12\x0e\n\x06txnAmt\x18\x02 \x01(\x05\x12\x0f\n\x07\x61\x63\x63Type\x18\x03 \x01(\t\x12\x0e\n\x06\x61\x63\x63\x41ge\x18\x04 \x01(\x05\x12\x13\n\x0b\x66laggedTxns\x18\x05 \x01(\x05\x12\x14\n\x0cmerchantType\x18\x06 \x01(\t\x12\x1a\n\x12geoCountryMismatch\x18\x07 \x01(\x08\x12\x15\n\rgeoDistanceKm\x18\x08 \x01(\x05\x12\x16\n\x0etimeGapLastTxn\x18\t \x01(\x03\x12\x16\n\x0eisAbnormalTime\x18\n \x01(\x08\x12\x17\n\x0fhighTxnVelocity\x18\x0b \x01(\x08\x12\x14\n\x0cuserAtvDelta\x18\x0c \x01(\x02\x12\x13\n\x0bisNewDevice\x18\r \x01(\x08\x12\x10\n\x08speedKmh\x18\x0e \x01(\x05\x12\x12\n\nfraudScore\x18\x0f \x01(\x02\x12\x0e\n\x06status\x18\x10 \x01(\t\x12\x10\n\x08\x63lientId\x18\x11 \x01(\tBB\n)org.example.springbootbackend.model.protoB\x13LiveSimulationProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'live_simulation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n)org.example.springbootbackend.model.protoB\023LiveSimulationProtoP\001'
  _globals['_LIVETRANSACTIONEVENTPROTO']._serialized_start=69
  _globals['_LIVETRANSACTIONEVENTPROTO']._serialized_end=281
  _globals['_LIVESIMULATIONENVELOPEPROTO']._serialized_start=284
  _globals['_LIVESIMULATIONENVELOPEPROTO']._serialized_end=440
  _globals['_LIVEINFERENCEEVENTPROTO']._serialized_start=443
  _globals['_LIVEINFERENCEEVENTPROTO']._serialized_end=814
# @@protoc_insertion_point(module_scope)
